import Head from "next/head";
import Nav from "../components/Navbar/navbar";
import Header from "../components/Header/header";
import styled from "styled-components";

const MainHeader = styled.div`
  background-color: #041553;
  color: white;
`;

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHeader>
        <Nav />
        <Header />
      </MainHeader>
    </div>
  );
};

export default Home;
